# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/software/CMake/3.11.1-GCCcore-6.4.0/bin/cmake

# The command to remove a file.
RM = /opt/software/CMake/3.11.1-GCCcore-6.4.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/home/ganjaisa/c_workspace/uart

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/home/ganjaisa/c_workspace/uart

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/software/CMake/3.11.1-GCCcore-6.4.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/software/CMake/3.11.1-GCCcore-6.4.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/home/ganjaisa/c_workspace/uart/CMakeFiles /mnt/home/ganjaisa/c_workspace/uart/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/home/ganjaisa/c_workspace/uart/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_uart

# Build rule for target.
test_uart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_uart
.PHONY : test_uart

# fast build rule for target.
test_uart/fast:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/build
.PHONY : test_uart/fast

#=============================================================================
# Target rules for targets named _uart

# Build rule for target.
_uart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _uart
.PHONY : _uart

# fast build rule for target.
_uart/fast:
	$(MAKE) -f CMakeFiles/_uart.dir/build.make CMakeFiles/_uart.dir/build
.PHONY : _uart/fast

src/test_uart.o: src/test_uart.c.o

.PHONY : src/test_uart.o

# target to build an object file
src/test_uart.c.o:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/src/test_uart.c.o
.PHONY : src/test_uart.c.o

src/test_uart.i: src/test_uart.c.i

.PHONY : src/test_uart.i

# target to preprocess a source file
src/test_uart.c.i:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/src/test_uart.c.i
.PHONY : src/test_uart.c.i

src/test_uart.s: src/test_uart.c.s

.PHONY : src/test_uart.s

# target to generate assembly for a file
src/test_uart.c.s:
	$(MAKE) -f CMakeFiles/test_uart.dir/build.make CMakeFiles/test_uart.dir/src/test_uart.c.s
.PHONY : src/test_uart.c.s

src/uart.o: src/uart.c.o

.PHONY : src/uart.o

# target to build an object file
src/uart.c.o:
	$(MAKE) -f CMakeFiles/_uart.dir/build.make CMakeFiles/_uart.dir/src/uart.c.o
.PHONY : src/uart.c.o

src/uart.i: src/uart.c.i

.PHONY : src/uart.i

# target to preprocess a source file
src/uart.c.i:
	$(MAKE) -f CMakeFiles/_uart.dir/build.make CMakeFiles/_uart.dir/src/uart.c.i
.PHONY : src/uart.c.i

src/uart.s: src/uart.c.s

.PHONY : src/uart.s

# target to generate assembly for a file
src/uart.c.s:
	$(MAKE) -f CMakeFiles/_uart.dir/build.make CMakeFiles/_uart.dir/src/uart.c.s
.PHONY : src/uart.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_uart"
	@echo "... edit_cache"
	@echo "... _uart"
	@echo "... src/test_uart.o"
	@echo "... src/test_uart.i"
	@echo "... src/test_uart.s"
	@echo "... src/uart.o"
	@echo "... src/uart.i"
	@echo "... src/uart.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

